package service

const API_INCORRECT_AUTH_HEADER string = "API_INCORRECT_AUTH_HEADER"
const API_INVALID_TOKEN string = "API_INVALID_TOKEN"

const API_REGISTER_INCORRECT_FIELDS = "API_REGISTER_INCORRECT_FIELDS"
const API_REGISTER_SUCCESS = "API_REGISTER_SUCCESS"
const API_REGISTER_EMAIL_ALREADY_EXISTS = "API_REGISTER_EMAIL_ALREADY_EXISTS"

const API_UNKNOW_ERROR = "API_UNKNOW_ERROR"

const API_LOGIN_INVALID_CREDENTIALS = "API_LOGIN_INVALID_CREDENTIALS"
const API_LOGIN_SUCCESS = "API_LOGIN_SUCCESS"
const API_LOGIN_EMAIL_NOT_REGISTERED = "API_LOGIN_EMAIL_NOT_REGISTERED"
