package utils

const API_INCORRECT_AUTH_HEADER = "API_INCORRECT_AUTH_HEADER"
const API_INVALID_TOKEN = "API_INVALID_TOKEN"

const API_REGISTER_INCORRECT_FIELDS = "API_REGISTER_INCORRECT_FIELDS"
const API_REGISTER_SUCCESS = "API_REGISTER_SUCCESS"
const API_REGISTER_EMAIL_ALREADY_EXISTS = "API_REGISTER_EMAIL_ALREADY_EXISTS"

const API_UNKNOW_ERROR = "API_UNKNOW_ERROR"

const API_LOGIN_INVALID_CREDENTIALS = "API_LOGIN_INVALID_CREDENTIALS"
const API_LOGIN_SUCCESS = "API_LOGIN_SUCCESS"
const API_LOGIN_EMAIL_NOT_REGISTERED = "API_LOGIN_EMAIL_NOT_REGISTERED"

const API_LOGOUT_SUCCESS = "API_LOGOUT_SUCCESS"

const API_CREATE_TASK_INCORRECT_FIELDS = "API_CREATE_TASK_INCORRECT_FIELDS"
const API_CREATE_TASK_SUCCESS = "API_CREATE_TASK_SUCCESS"
const API_ALL_TASKS_SUCCESS = "API_ALL_TASKS_SUCCESS"
const API_DELETE_TASK_SUCCESS = "API_DELETE_TASK_SUCCESS"
const API_UPDATE_TASK_INCORRECT_FIELDS = "API_UPDATE_TASK_INCORRECT_FIELDS"
const API_UPDATE_TASK_SUCCESS = "API_UPDATE_TASK_SUCCESS"
const API_NOT_FOUND_TASK_SUCCESS = "API_NOT_FOUND_TASK_SUCCESS"