package utils

const (
	API_INCORRECT_AUTH_HEADER = "API_INCORRECT_AUTH_HEADER"
	API_INVALID_TOKEN = "API_INVALID_TOKEN"

	API_REGISTER_INCORRECT_FIELDS = "API_REGISTER_INCORRECT_FIELDS"
	API_REGISTER_SUCCESS = "API_REGISTER_SUCCESS"
	API_REGISTER_EMAIL_ALREADY_EXISTS = "API_REGISTER_EMAIL_ALREADY_EXISTS"

	API_LOGIN_INVALID_CREDENTIALS = "API_LOGIN_INVALID_CREDENTIALS"
	API_LOGIN_SUCCESS = "API_LOGIN_SUCCESS"
	API_LOGIN_EMAIL_NOT_REGISTERED = "API_LOGIN_EMAIL_NOT_REGISTERED"

	API_LOGOUT_SUCCESS = "API_LOGOUT_SUCCESS"

	API_CREATE_TASK_INCORRECT_FIELDS = "API_CREATE_TASK_INCORRECT_FIELDS"
	API_CREATE_TASK_SUCCESS = "API_CREATE_TASK_SUCCESS"
	API_ALL_TASKS_SUCCESS = "API_ALL_TASKS_SUCCESS"
	API_DELETE_TASK_SUCCESS = "API_DELETE_TASK_SUCCESS"
	API_UPDATE_TASK_INCORRECT_FIELDS = "API_UPDATE_TASK_INCORRECT_FIELDS"
	API_UPDATE_TASK_SUCCESS = "API_UPDATE_TASK_SUCCESS"
	API_NOT_FOUND_TASK = "API_NOT_FOUND_TASK"
)